{{/* vim: set filetype=mustache: */}}

{{ include "shortlink-common.ServiceAccount" . }}

{{ include "shortlink-common.Deployment" . }}

{{ include "shortlink-common.Service" . }}

{{ include "shortlink-common.PodDisruptionBudget" . }}

{{ include "shortlink-common.NetworkPolicy" . }}
