apiVersion: v1
kind: Secret
metadata:
  name: shop-postgres-datasource
  labels:
    grafana_datasource: 'true'
stringData:
  postgres.yaml: |-
    apiVersion: 1
    datasources:
      - name: PostgreSQL (shop)
        type: postgres
        uid: shop-postgres-datasource
        url: shop-postgres-pgbouncer.shortlink-shop:5432
        user: grafana
        database: shop
        access: proxy
        basicAuth: false
        editable: false
        jsonData:
          connMaxLifetime: 14400
          maxIdleConns: 100
          maxIdleConnsAuto: true
          maxOpenConns: 100
          postgresVersion: 1800
          sslmode: require
          timescaledb: true
        secureJsonData:
          password: 'grafana-password'
