apiVersion: v2
appVersion: "1.0.0"
name: oms-graphql
description: ShortLink Shop OMS GraphQL Subgraph (Tailcall) - gRPC to GraphQL
version: 0.1.0
kubeVersion: ">= 1.30.0 || >= v1.30.0-0"
keywords:
  - graphql
  - oms
  - tailcall
  - subgraph
  - cart
  - grpc
home: https://github.com/shortlink-org/shortlink
sources:
  - https://github.com/shortlink-org/shortlink
maintainers:
  - email: batazor111@gmail.com
    name: batazor
    url: batazor.ru
engine: gotpl
type: application
deprecated: false
dependencies:
  - name: shortlink-template
    version: 0.12.1
    repository: oci://ghcr.io/shortlink-org/charts
