apiVersion: v2
appVersion: "1.0.0"
name: temporal
version: 0.3.0
kubeVersion: ">= 1.30.0 || >= v1.30.0-0"
keywords:
  - temporal
  - background_job
maintainers:
  - email: batazor111@gmail.com
    name: batazor
    url: batazor.ru
type: application
deprecated: false
dependencies:
  - name: shortlink-template
    version: 0.12.1
    repository: oci://ghcr.io/shortlink-org/charts
  - name: temporal
    version: 0.73.1
    repository: https://go.temporal.io/helm-charts
    condition: temporal.enabled
    tags:
      - temporal
      - background_job
