apiVersion: v2
appVersion: "1.0.0"
name: courier-emulation
description: ShortLink Courier Emulation service for delivery simulation
version: 0.1.0
kubeVersion: ">= 1.30.0 || >= v1.30.0-0"
keywords:
  - courier
  - emulation
  - delivery
  - shop
  - shortlink
home: https://github.com/shortlink-org/shortlink
sources:
  - https://github.com/shortlink-org/shortlink
maintainers:
  - email: batazor111@gmail.com
    name: batazor
    url: batazor.ru
engine: gotpl
type: application
deprecated: false
dependencies:
  - name: shortlink-template
    version: 0.12.0
    repository: oci://ghcr.io/shortlink-org/charts
