{{- if .Values.requestAuthentication.enabled }}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: temporal-web-jwt
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: temporal
      app.kubernetes.io/component: web
  jwtRules:
    - issuer: {{ .Values.requestAuthentication.issuer | quote }}
      jwksUri: {{ .Values.requestAuthentication.jwksUri | quote }}
      forwardOriginalToken: {{ .Values.requestAuthentication.forwardOriginalToken | default true }}
      outputClaimToHeaders:
        - header: "x-user-id"
          claim: "sub"
        - header: "x-user-email"
          claim: "email"
{{- end }}
