{{- if .Values.temporal.enabled }}
{{- $saName := .Values.temporal.serviceAccount.name | default .Values.temporal.fullnameOverride | default "temporal" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: temporal
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
{{- end }}
