[package]
name = "delivery"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12"
prost-types = "0.12"
pbjson-types = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tonic = "0.11"
tokio = { version = "1", features = ["full"] }
shortlink-org_shop-oms_community_neoeinstein-tonic = { version = "0.4.1-20251129220001-af22ed6b9578.1", registry = "buf" }

[build-dependencies]
prost-build = "0.12"

